import { Navbar, Footer } from "@/components/export";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Amanda et Quentin",
  description: "Generated by create next app",
};

export const revalidate = 30 // revalidate at most every hour

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>

    </html>
  );
}
